### ISSUE TITLE
Object not found for 11.7.2

### ISSUE THREAD

**Issue by Jrogan23** [mikemeredith/AHM_code#2]
Hi, in section 11.7.2, I am running into this error when trying to enter this code:

str(win.data <- list(y = yaug, nsite = dim(y)[1], nrep = dim(y)[2],
                     nspec = dim(y)[3], nz = nz, M = nspec + nz, ele = ele, forest = forest,
                     DAT = DAT, DUR = DUR) )

error message:

Error in str(win.data <- list(y = yaug, nsite = dim(y)[1], nrep = dim(y)[2],  : 
  object 'DAT' not found

I have the AHM book package loaded, I'm not sure if the object name was changed. When I look at the MHB2014 dataset, I see "date" and "dur" listed as objects, but not DAT and DUR. I actually tried substituting these for DAT and DUR but received the error message:

Error in str(win.data <- list(y = yaug, nsite = dim(y)[1], nrep = dim(y)[2],  : 
  object 'dur' not found

I'm not sure what I'm missing, any help appreciated! Thanks!!

**Comment by mikemeredith** [comment]
This must refer to file "AHM1_11.07.R", lines 190-193.

Please look at the block of code at the head of the script. The objects `DAT` and `DUR` are created on lines 36 and  42.

**Comment by Jrogan23** [comment]
Yes, thank you!! At times when I reload R I'm unsure of what code from previous exercises need to be re-entered. I'll be sure to check that more thoroughly in the future,
