### ISSUE TITLE
calculation of chi2 in GOF test for DYNOCC models

### ISSUE THREAD

**Issue by efkleiven** [mikemeredith/AHM_code#5]
Dear Mike,

First of all, thanks a lot for sharing the codes from the AHM-book. It has been incredibly helpful for my work.
I have recently tried to do a model check of a dynamic occupancy model based on your code AHM_code/AHM2_ch04/AHM2_04.08.R. On line 197-205 in the code, chi2 is calculated. I apologize if there is something I'm missing, but it seems to me like the chi2 is estimated as: (observed - expected)^2 / observed, instead of the typical way of estimating chi2 :(observed - expected)^2 / expected. Is it a reason for this or am I missing something?

Best Regards,
Eivind

**Comment by mikemeredith** [comment]
I'll have to pass that question to the authors. This is the code used to produce Fig. 4.12 in the book.

**Comment by mikemeredith** [comment]
Marc Kéry confirms that this is an error - and thanks for spotting and reporting it! He will add it to the [corrections page](https://sites.google.com/site/appliedhierarchicalmodeling/errata) for the book and I'll correct the online code shortly.

**Comment by mikemeredith** [comment]
Now  done.
